# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Deploy actions/setup-node

on:
  push:
    branches:
      - main

jobs: 
  deploy: 
    runs-on: ubuntu-22.04
    name: Deploy API to Cloudflate Workers
    steps: 
      - uses: actions/checkout@v3
        with: 
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with: 
          node-version: 18
      - uses: cloudflare/wrangler-action@2.0.0
        with: 
          apiToken: ${{ secrets.CF_API_TOKEN }}